title: Marek-MC.github.io
description: Mareks beautiful website. 
baseurl: "Marek-MC.github.io"
url: "https://Marek-MC.github.io"

theme: cvless

# site settings
taglong: Marek-MCs beautiful internet CV.
tagshort: Marek-MC
cv: true

# author settings
author:
  name: Marek Carlisle
  email: MarekCarlisle@Protonmail.com
photo: assets/files/photo.jpg
address: Fargo, ND
phone: +(218) 329-9879

# profile links
profile:

  bluesky: https://bsky.app/profile/username.bsky.social
  instagram: https://www.instagram.com/username
  linkedin: https://www.linkedin.com/in/username
  github: https://github.com/username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
